apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mafiascum
  namespace: ccatlett2000
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mafiascum
        version: demo
    spec:
      containers:
      - name: mafiascum
        image: ccatlett2000/mafiascum:demo
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: DB_HOST
          value: mariadb
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: ms_phpbb3
        - name: DB_USER
          value: root
        - name: DB_PASS
          value: examplepass
---
apiVersion: v1
kind: Service
metadata:
  name: mafiascum
  namespace: ccatlett2000
  labels:
    app: mafiascum
    version: demo
spec:
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: mafiascum
    version: demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mafiascum-demo
  namespace: ccatlett2000
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - mafiascum-demo.mctherealm.net
    secretName: mafiascum-demo-tls
  rules:
  - host: mafiascum-demo.mctherealm.net
    http:
      paths:
      - path: /
        backend:
          serviceName: mafiascum
          servicePort: 80
